### ISSUE TITLE
Mega missing file - don't close if you didn't fix it

### ISSUE THREAD

**Issue by Mushinigami** [TitansBane/Elysium#156]
Got error:

31.43 - File hash check (-42) c743545f34e5a5a535d35d32493afad9bc20920cb3eccd873b029827dfe015bd
31.53 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/ENcDgALD#Nbp79H9euhQLfV4icgT2dgWdImo7GNupoWu1Ijt4Epc failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 225
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181

Another user got a similar a couple of hours ago and issue was closed without solution.

**Comment by Mushinigami** [comment]
Issue apparently was fixed.
