### ISSUE TITLE
Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)

### ISSUE THREAD

**Issue by clausagerskov** [TitansBane/Elysium#167]
Relevant line of log:
1337.8 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
1338.94 - Hashed download is incorrect
1338.94 - Loading for alternative to U659DN1scQM=
1339 - No alternative for U659DN1scQM= could be found
1339.04 - Hashing Remaining Archives
1339.04 - Looking for files to hash
1339.23 - Found 1656 total files, 1478 matching filesize
1339.71 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
1339.71 - Cannot continue, was unable to download one or more archives
1339.71 - File hash check (-42) e57d84127e2c0d433d9fa4f23a967b1e8ae7a55b2fec0d3a0d97e879a56139d8
1339.72 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1340.3 - File hash check (-42) e57d84127e2c0d433d9fa4f23a967b1e8ae7a55b2fec0d3a0d97e879a56139d8

**Comment by J0hnyb0x** [comment]
I had the same problem.
i found a other side to download "TUDM - The Ultimate Dodge Mod v4 x64.rar"
https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw
i downloaded it and replace it in the Elysium/downloads folder

**Comment by clausagerskov** [comment]
sure thats a workaround for now should still be fixed though

**Comment by In2darabbithole** [comment]
The same thing happened to me while downloading Living Skyrim, earlier this afternoon. So, the problem might be on the other end.

**Comment by rene0121** [comment]
same downloading and replacing the 7zip myself helped fix it.

**Comment by chughes08** [comment]
I recently tried the steps to re-download it and it still didnt work what should i do?

**Comment by In2darabbithole** [comment]
https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw
Download the file manually from there and put it in the mods file.

**Comment by chughes08** [comment]
i have no "mods" folder only a downloads folder in the elysium folder

**Comment by In2darabbithole** [comment]
![133820997-80fa7bef-cc55-4334-a438-19f4c93520a6](https://user-images.githubusercontent.com/91040272/134408762-723eace5-10b2-4801-ad4c-774dd002b4d8.jpg)
Click on this and drop the zip in this file.

**Comment by glendaion** [comment]
I'm having more problems with hashing with a lot of files:

666,38 - Found 1529 total files, 1496 matching filesize
666,67 - Unable to download Elysium - Dyndolod 3D Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output.7z_496ad9f4-b382-4bc7-9eca-196e39452c51)
666,67 - Unable to download Elysium - Dyndolod 3D Output (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output (Creation Club).7z_029e773a-65e9-4a34-833f-a66cfd574c2a)
666,67 - Unable to download Elysium - Dyndolod 3D Output - Performance Mode.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output - Performance Mode.7z_58b3d958-f9c1-4c2c-977e-a58ba733e38d)
666,67 - Unable to download Elysium - Dyndolod 3D Output - Performance Mode (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Elysium - Dyndolod 3D Output - Performance Mode (Creation Club).7z_564a7ab8-bf62-4cb5-b43b-86601b8a3c52)
666,67 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
666,67 - Unable to download Grass Cache Generated Files.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Grass Cache Generated Files.7z_2e01315f-033e-498f-8777-e24899bbab39)
666,67 - Unable to download Grass Cache Generated Files (Creation Club).7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Grass Cache Generated Files (Creation Club).7z_dc53b3b0-fcca-45c6-9800-b5dae69bb31e)
666,67 - Cannot continue, was unable to download one or more archives
666,68 - File hash check (-42) 03ddc69a301028b888bb9e4c08476af7923efb959b6c65ab312f0635eda80720
666,71 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
667,3 - File hash check (-42) 03ddc69a301028b888bb9e4c08476af7923efb959b6c65ab312f0635eda80720

**Comment by Elite2Delete** [comment]
Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
381,4 - Cannot continue, was unable to download one or more archives
382,32 - File hash check (-42) 552d83690160c28b65c0f1a1316cae32ef9f649b34c05dfd823ef642db2464f0
383,49 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
383,49 - File hash check (-42) 552d83690160c28b65c0f1a1316cae32ef9f649b34c05dfd823ef642db2464f0

This is ruine for me) Help pls
