### ISSUE TITLE
Cannot download TUDM - The Ultimate Dodge Mod v4 x64.rar

### ISSUE THREAD

**Issue by caddickdaniel** [TitansBane/Elysium#188]
Mod author seems to have made it private on their google drive link, is there anyway you can provide a manual download for it?

1259.65 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
1260.46 - Hashed download is incorrect
1260.46 - Loading for alternative to U659DN1scQM=
1260.5 - No alternative for U659DN1scQM= could be found
1261.14 - Hashing Remaining Archives
1261.14 - Looking for files to hash
1261.22 - Found 1529 total files, 1497 matching filesize
1261.43 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
1261.44 - Cannot continue, was unable to download one or more archives

**Comment by Malazanrake** [comment]
thanks  so You manual download it and then copy it into C:\Elysium\downloads ?

**Comment by Malazanrake** [comment]
Hi caddick, thanks again, please try this 
https://drive.google.com/file/d/0B2VgBVA9jE6RTjJiYnRTTE9qRUE/view?resourcekey=0-atMbrLF_HPd3ogbiZaBiXw
for The Ultimate Dodge Mod v4 x64.rar

**Comment by Elite2Delete** [comment]
Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
381,4 - Cannot continue, was unable to download one or more archives
382,32 - File hash check (-42) 552d83690160c28b65c0f1a1316cae32ef9f649b34c05dfd823ef642db2464f0
383,49 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
at Wabbajack.Lib.ABatchProcessor.b__66_0() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<b__0>d.MoveNext() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
383,49 - File hash check (-42) 552d83690160c28b65c0f1a1316cae32ef9f649b34c05dfd823ef642db2464f0

This is ruine for me) Help pls
