### ISSUE TITLE
 Installation problem

### ISSUE THREAD

**Issue by BezmambI** [TitansBane/Elysium#199]
Error
"2741,09 - Getting Lovers Lab Login
2741,2 - (Retry 2 of 5), got exception (2) Не удается найти указанный файл: [C:\Users\ivanr\AppData\Local\Wabbajack\nexusapikey], waiting 200ms
2741,41 - (Retry 3 of 5), got exception (2) Не удается найти указанный файл: [C:\Users\ivanr\AppData\Local\Wabbajack\nexusapikey], waiting 400ms
2741,81 - (Retry 4 of 5), got exception (2) Не удается найти указанный файл: [C:\Users\ivanr\AppData\Local\Wabbajack\nexusapikey], waiting 800ms
2742,62 - (Retry 5 of 5), got exception (2) Не удается найти указанный файл: [C:\Users\ivanr\AppData\Local\Wabbajack\nexusapikey], waiting 1600ms
2744,24 - Getting User's Nexus API Key"
And what about Lovers Lab, I just don't load it at the installation 
![Screenshot_1](https://user-images.githubusercontent.com/93486835/139595111-23c5dfae-b3e1-46f1-86fc-e3acd3fdfc07.png)

**Comment by medinaKrom1** [comment]
Hi. If the modlist needs a loverslab account because a mod comes from there just create an account for free on loverslab).
Maybe you need it earlier or later)).

**Comment by BezmambI** [comment]
> Hi. If the modlist needs a loverslab account because a mod comes from there just create an account for free on loverslab). Maybe you need it earlier or later)).

I already have it created and I log in to it, and then this white screen. No matter how much I wait, it does not disappear.

**Comment by focused** [comment]
Use VPN to solve it, connections from some countries lead to the white screen, but it works for others. Switch on VPN, go to settings, log in to LL, then you can safely switch off and continue the installation.

**Comment by focused** [comment]
Also, you may try to check "network workaround" in settings instead of VPN.

**Comment by focused** [comment]
@BezmambI create an account at LL and then try my solution, it worked for me.

**Comment by BezmambI** [comment]
There was a new error

741,27 - Loading server whitelist
741,53 - Loaded permissions for 568 servers and 262 Google Drive files
741,53 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
741,54 - 
742,35 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
743,15 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
743,95 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
744,72 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
745,52 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
746,3 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
747,09 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
1152,49 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
1152,65 - Encountered error, can't continue - System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Wabbajack.Lib.Downloaders.ManualDownloader.State.Download(Archive a, AbsolutePath destination) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\ManualDownloader.cs:line 57
   at Wabbajack.Lib.AInstaller.DownloadMissingArchives(List`1 missing, Boolean download) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 239
   at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 228
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1153,31 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
