### ISSUE TITLE
Download Issues With Multiple Files

### ISSUE THREAD

**Issue by CrypticFuzz** [TitansBane/Elysium#203]
17.77 - Loaded permissions for 568 servers and 262 Google Drive files
17.77 - File hash check (-42) b3a905def33fe6211259f16c5ae23d497979bddf9b23a0d59cc2912d6862ac7d
17.79 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
17.8 - Downloading Rudy ENB CW Zangdar's Edit ReShade preset.7z
17.8 - Downloading Elysium - Core Files.7z
18.09 - File hash check (-42) b3a905def33fe6211259f16c5ae23d497979bddf9b23a0d59cc2912d6862ac7d
18.88 - Hashed download is incorrect
18.88 - Loading for alternative to U659DN1scQM=
18.97 - No alternative for U659DN1scQM= could be found
315.44 - Hashing Remaining Archives
315.44 - Looking for files to hash
315.52 - Found 1556 total files, 1548 matching filesize
315.72 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
315.72 - Cannot continue, was unable to download one or more archives
315.72 - File hash check (-42) b3a905def33fe6211259f16c5ae23d497979bddf9b23a0d59cc2912d6862ac7d
315.81 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
316.13 - File hash check (-42) b3a905def33fe6211259f16c5ae23d497979bddf9b23a0d59cc2912d6862ac7d

Where would I get these missing files? Wabbajack has been a tough experience so far. I have a data cap and tried one modpack already and that failed. Now I tried another, any help would be great!

**Comment by focused** [comment]
See pins in the channel! https://discord.com/channels/552625087438782474/882031813676126298/887943409250213918
