### ISSUE TITLE
There was a new error

### ISSUE THREAD

**Issue by BezmambI** [TitansBane/Elysium#205]
There was a new error

741,27 - Loading server whitelist
741,53 - Loaded permissions for 568 servers and 262 Google Drive files
741,53 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
741,54 -
742,35 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
743,15 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
743,95 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
744,72 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
745,52 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
746,3 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
747,09 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
1152,49 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa
1152,65 - Encountered error, can't continue - System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Wabbajack.Lib.Downloaders.ManualDownloader.State.Download(Archive a, AbsolutePath destination) in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\Downloaders\ManualDownloader.cs:line 57
at Wabbajack.Lib.AInstaller.DownloadMissingArchives(List`1 missing, Boolean download) in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 239
at Wabbajack.Lib.AInstaller.DownloadArchives() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 228
at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 144
at Wabbajack.Lib.ABatchProcessor.b__66_0() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<b__0>d.MoveNext() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1153,31 - File hash check (-42) bb91604d51f1a486bd08451d3caee2387d4c76f83b83b896033220fb3b493caa

The problem is that for some reason this archive was swinging for a very long time, and once again my Wabbajack closed, sometimes due to the fact that I opened and minimized the window with this application. I sat and did not touch this application because of the danger, but this file took too long to load, sometimes I looked. Once again, I started the download process again and this archive began to download, only after the last flight I already gave this error.
P.S.
Sorry for my English right away, this entire text has been translated in a translator.

**Comment by focused** [comment]
Maybe ask at https://discord.com/channels/552625087438782474/882031813676126298 ?
