### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by DraugrReign** [TitansBane/Elysium#206]
17408.68 - Downloading TUDM - The Ultimate Dodge Mod v4 x64.rar
17408.89 - File hash check (-42) dbfafe2a9b2bb6cf7a8b52194b74dcaf57ed54b30e03417d8c8647750337d2e8
17409.77 - Hashed download is incorrect
17409.77 - Loading for alternative to U659DN1scQM=
17409.91 - No alternative for U659DN1scQM= could be found
17439.24 - Hashed download is incorrect
17439.24 - Loading for alternative to XTaNNFIm3eM=
17439.31 - No alternative for XTaNNFIm3eM= could be found
17439.46 - Hashing Remaining Archives
17439.46 - Looking for files to hash
17440.03 - Found 1576 total files, 1551 matching filesize
17441.32 - Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)
17441.32 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
17441.32 - Cannot continue, was unable to download one or more archives
17441.32 - File hash check (-42) dbfafe2a9b2bb6cf7a8b52194b74dcaf57ed54b30e03417d8c8647750337d2e8
17441.32 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
17441.68 - File hash check (-42) dbfafe2a9b2bb6cf7a8b52194b74dcaf57ed54b30e03417d8c8647750337d2e8
17464.61 - Loading ModLists from GitHub

**Comment by blondeblindguy** [comment]
I'm having the same issue: Unable to download TUDM - The Ultimate Dodge Mod v4 x64.rar (GoogleDriveDownloader+State|0B2VgBVA9jE6RTjJiYnRTTE9qRUE)

**Comment by focused** [comment]
See pins at discord channel https://discord.com/invite/VVHRJeK

**Comment by TDennyDray** [comment]
> See pins at discord channel https://discord.com/invite/VVHRJeK

Dude i know this Discord channel ... Thats easy a World of warcraft server discord channel just with the 
name Elysium xD

**Comment by focused** [comment]
Oops, my fault, try this one https://discord.gg/9meHMG3y, I've copied it from the right channel just now.
![image](https://user-images.githubusercontent.com/1449828/140381448-6509f978-de2c-4cb8-bd34-ff3a7d5884c4.png)

**Comment by TDennyDray** [comment]
> Oops, my fault, try this one https://discord.gg/9meHMG3y, I've copied it from the right channel just now.
> 
> ![image](https://user-images.githubusercontent.com/1449828/140381448-6509f978-de2c-4cb8-bd34-ff3a7d5884c4.png)

This is right and really helpfull! Thanks for the effort of supporting these people with their problems :)
