### ISSUE TITLE
Unable to download xLODGen.84.7z

### ISSUE THREAD

**Issue by Skyppa** [TitansBane/Elysium#241]
Hello everybody, i have a problem for my installation...
an idea ?

0,21 - Wabbajack Build - f0820514e7dfce84303dde8ef09257bdbbf59c25
0,21 - Running in D:\Wabbajack\2.5.3.3
0,21 - Detected Windows Version: 10.0.22000.0
0,22 - System settings - (16GB RAM) (10GB Page), Display: 1920 x 1080 (11,9GB VRAM - VideoMemorySizeMb=10240)
0,22 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0,23 - Getting new Wabbajack version list
0,24 - Steam: Found game Fallout: New Vegas (22380) at "D:\Steam\steamapps\common\Fallout New Vegas"
0,24 - Steam: Found game RimWorld (294100) at "D:\Steam\steamapps\common\RimWorld"
0,24 - Steam: Found game Fallout 4 (377160) at "D:\Steam\steamapps\common\Fallout 4"
0,24 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Steam\steamapps\common\Skyrim Special Edition"
0,24 - Steam: Found game Counter-Strike: Global Offensive (730) at "D:\Steam\steamapps\common\Counter-Strike Global Offensive"
0,24 - Steam: Found game Among Us (945360) at "D:\Steam\steamapps\common\Among Us"
0,24 - Steam: Found game Crab Game (1782210) at "C:\Program Files (x86)\Steam\steamapps\common\Crab Game"
0,24 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared"
0,24 - Steam: Found game Sid Meier's Pirates! (3920) at "C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Pirates!"
0,24 - Steam: Found game Crab Game (1782210) at "c:/program files (x86)/steam\steamapps\common\Crab Game"
0,24 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/program files (x86)/steam\steamapps\common\Steamworks Shared"
0,24 - Steam: Found game Sid Meier's Pirates! (3920) at "c:/program files (x86)/steam\steamapps\common\Sid Meier's Pirates!"
0,24 - GOG: RegistryKey HKEY_LOCAL_MACHINE\Software\WOW6432Node\GOG.com\Games\1448452156 does not have a value BUILDID
0,24 - BethNet: Found game Creation Kit: Skyrim (10) at "D:\Steam\steamapps\common\Skyrim Special Edition"
0,26 - EpicGamesStore: Found game Borderlands 3 at "D:\Borderlands 3\Borderlands3"
0,26 - EpicGamesStore: Found game Control at "D:\Control"
0,26 - EpicGamesStore: Found game Just Cause 4 at "E:\JustCause4"
0,26 - EpicGamesStore: Found game Grand Theft Auto V at "C:\GTAV"
0,26 - EpicGamesStore: Found game HITMAN at "E:\HITMAN"
0,26 - EpicGamesStore: Found game Grand Theft Auto V at "D:\GTAV"
0,26 - EpicGamesStore: Found game Batman™ Arkham Knight at "C:\BatmanArkhamKnight"
0,26 - EpicGamesStore: Found game Batman™ Arkham City - Game of the Year Edition at "D:\BatmanArkhamCity"
0,56 - Wabbajack Version: 2.5.3.3
1,05 - Build server is down
1,07 - Build server is down
1,55 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\Battlefield 2042 Open Beta for Game Origin.OFR.50.0004592
1,56 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\Battlefield 2042 Open Beta for Game Origin.OFR.50.0004592
1,56 - Origin: Game Origin.OFR.50.0004592 was found using the Api but has no Path
1,83 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\Battlefield V for Game Origin.OFR.50.0002683
1,83 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\Battlefield V for Game Origin.OFR.50.0002683
1,83 - Origin: Game Origin.OFR.50.0002683 was found using the Api but has no Path
2,19 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\Criterion\BurnoutPR for Game Origin.OFR.50.0002535
2,19 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\Criterion\BurnoutPR for Game Origin.OFR.50.0002535
2,19 - Origin: Game Origin.OFR.50.0002535 was found using the Api but has no Path
2,23 - Loading ModLists from GitHub
2,59 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry32\SOFTWARE\EA Games\Need for Speed Payback for Game Origin.OFR.50.0002167
2,59 - Origin: Unable to open subkey HKEY_LOCAL_MACHINE@Registry64\SOFTWARE\EA Games\Need for Speed Payback for Game Origin.OFR.50.0002167
2,59 - Origin: Game Origin.OFR.50.0002167 was found using the Api but has no Path
2,89 - Origin: RegistryKey HKEY_LOCAL_MACHINE\SOFTWARE\Maxis\The Sims 4 does not have a value Install Dir
2,89 - Origin: RegistryKey HKEY_LOCAL_MACHINE\SOFTWARE\Maxis\The Sims 4 does not have a value Install Dir
2,89 - Origin: Game Origin.OFR.50.0000589 was found using the Api but has no Path
2,89 - Origin: Found game Apex Legends - PC - WW (Origin) (Origin.OFR.50.0002694) at "E:\Apex"
2,89 - Origin: Found game KINGSTON (WEST EU) - PC - WW (Origin.OFR.50.0004540) at "E:\Battlefield 2042"
2,89 - Origin: Found game KINGSTON - OPEN BETA - PC - WW (Origin.OFR.50.0004592) at ""
2,89 - Origin: Found game Battlefield V Standard Edition - PC - ROW (Origin) (Origin.OFR.50.0002683) at ""
2,89 - Origin: Found game Burnout™ Paradise Remastered - PC - WEST EU/ANZ (Origin) (Origin.OFR.50.0002535) at ""
2,89 - Origin: Found game Need for Speed Payback Deluxe Edition - PC - ROW (Origin.OFR.50.0002167) at ""
2,89 - Origin: Found game THE SIMS 4 ORIGIN FREE TRIAL WW (Origin.OFR.50.0000589) at ""
27,21 - Starting to install Elysium
27,22 - Cleaning VFS, this may take a bit of time
27,26 - Starting Installer Task
27,26 - Installation has Started
27,26 - Configuring Processor
27,26 - Install Folder: D:\Elysium
27,27 - Downloads Folder: D:\Elysium\downloads
27,27 - Game Folder: D:\Steam\steamapps\common\Skyrim Special Edition
27,27 - Wabbajack Folder: D:\Wabbajack\2.5.3.3
27,27 - Drive watcher is starting. Will warn at 8GB and error at 4GB
27,27 - Starting Drive watcher on D:\ currently 149,4GB free out of 931,5GB
27,27 - Validating Game ESMs
27,3 - Creating Output Folders
27,44 - Optimizing ModList
27,44 - Optimizing ModList directives
31,24 - Looking for files to delete
31,28 - Cleaning empty folders
32,33 - Looking for unmodified files
34,19 - Updating ModList
34,19 - Optimized 241594 directives to 241594 required
34,25 - Hashing Archives
34,25 - Looking for files to hash
34,31 - Found 1559 total files, 1550 matching filesize
34,52 - Downloading Missing Archives
34,52 - Missing 1 archives
34,52 - Getting Nexus API Key, if a browser appears, please accept
34,53 - Loading server whitelist
35,32 - Loaded permissions for 608 servers and 269 Google Drive files
35,39 - Downloading xLODGen.84.7z
37,79 - Loading for alternative to Ypeg2MKgzlQ=
37,99 - No alternative for Ypeg2MKgzlQ= could be found
38,08 - Hashing Remaining Archives
38,08 - Looking for files to hash
38,14 - Found 1559 total files, 1550 matching filesize
38,41 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
38,41 - Cannot continue, was unable to download one or more archives
38,42 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383

**Comment by Skyppa** [comment]
https://github.com/TitansBane/Elysium/issues/239
