### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by EDDIE2Fast** [TitansBane/Elysium#246]
Hi, everyone,

unfortunately Elysium can no longer be installed.
The version has been patched, but there appears to be an issue with the versions.

Follow the log:

0,19 - Wabbajack Build - fed371a6f1956ee74801c18be22a6d628c68bc0f
0,19 - Running in E:\Skyrim Wabbaajack
0,2 - Detected Windows Version: 10.0.19042.0
0,2 - System settings - (31,9GB RAM) (0B Page), Display: 3840 x 1080 (23,8GB VRAM - VideoMemorySizeMb=10240)
0,2 - Pagefile is disabled! Consider increasing to 20000MB. A disabled pagefile can cause crashes and poor in-game performance.
0,2 - Outside of standard install folder, not updating
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key appid
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key name
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key installdir
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key LastUpdated
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key SizeOnDisk
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key BytesToDownload
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key BytesDownloaded
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key BytesToStage
0,23 - Steam: ACF Manifest at H:\SteamLibrary\steamapps\appmanifest_759740.acf does not contain a value with key BytesStaged
0,24 - Steam: ACF Manifest at D:\Steam\steamapps\appmanifest_244210.acf does not contain a value with key BytesToStage
0,24 - Steam: ACF Manifest at D:\Steam\steamapps\appmanifest_244210.acf does not contain a value with key BytesStaged
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key appid
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key name
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key installdir
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key LastUpdated
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key SizeOnDisk
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesToDownload
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesDownloaded
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesToStage
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesStaged
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key appid
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key name
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key installdir
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key LastUpdated
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key SizeOnDisk
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesToDownload
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesDownloaded
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesToStage
0,25 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesStaged
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key appid
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key name
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key installdir
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key LastUpdated
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key SizeOnDisk
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesToDownload
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesDownloaded
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesToStage
0,29 - Steam: ACF Manifest at G:\Steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesStaged
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key appid
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key name
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key installdir
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key LastUpdated
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key SizeOnDisk
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesToDownload
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesDownloaded
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesToStage
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_107410.acf does not contain a value with key BytesStaged
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key appid
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key name
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key installdir
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key LastUpdated
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key SizeOnDisk
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesToDownload
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesDownloaded
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesToStage
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_221100.acf does not contain a value with key BytesStaged
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key appid
0,29 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key name
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key installdir
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key LastUpdated
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key SizeOnDisk
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesToDownload
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesDownloaded
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesToStage
0,3 - Steam: ACF Manifest at g:/steam\steamapps\appmanifest_571740.acf does not contain a value with key BytesStaged
0,3 - Steam: Found game Arma 3 (107410) at "H:\SteamLibrary\steamapps\common\Arma 3"
0,3 - Steam: Found game RAILROADS Online! (1696810) at "H:\SteamLibrary\steamapps\common\Railroads Online"
0,3 - Steam: Found game Assetto Corsa (244210) at "H:\SteamLibrary\steamapps\common\assettocorsa"
0,3 - Steam: Found game BeamNG.drive (284160) at "H:\SteamLibrary\steamapps\common\BeamNG.drive"
0,3 - Steam: Found game Fallout 4 (377160) at "H:\SteamLibrary\steamapps\common\Fallout 4"
0,3 - Steam: Found game Hunt: Showdown (594650) at "H:\SteamLibrary\steamapps\common\Hunt Showdown"
0,3 - Steam: Found game Professional Farmer: Cattle and Crops (704030) at "H:\SteamLibrary\steamapps\common\Cattle and Crops"
0,3 - Steam: Found game Among Us (945360) at "H:\SteamLibrary\steamapps\common\Among Us"
0,3 - Steam: Found game Spyro™ Reignited Trilogy (996580) at "H:\SteamLibrary\steamapps\common\Spyro Reignited Trilogy"
0,3 - Steam: Found game Skyrim Script Extender (SKSE) (365720) at "D:\Steam\steamapps\common\skyrim"
0,3 - Steam: Found game DiRT Rally 2.0 (690790) at "D:\Steam\steamapps\common\DiRT Rally 2.0"
0,3 - Steam: Found game RIDE 4 (1259980) at "I:\SteamLibrary\steamapps\common\RIDE 4"
0,3 - Steam: Found game Distance (233610) at "I:\SteamLibrary\steamapps\common\Distance"
0,3 - Steam: Found game Tabletop Simulator (286160) at "I:\SteamLibrary\steamapps\common\Tabletop Simulator"
0,3 - Steam: Found game The Witcher 3: Wild Hunt (292030) at "I:\SteamLibrary\steamapps\common\The Witcher 3"
0,3 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "I:\SteamLibrary\steamapps\common\Skyrim Special Edition"
0,3 - Steam: Found game Half-Life: Alyx (546560) at "I:\SteamLibrary\steamapps\common\Half-Life Alyx"
0,3 - Steam: Found game Hell Let Loose (686810) at "I:\SteamLibrary\steamapps\common\Hell Let Loose"
0,3 - Steam: Found game Assetto Corsa Competizione (805550) at "I:\SteamLibrary\steamapps\common\Assetto Corsa Competizione"
0,3 - Steam: Found game Gang Beasts Soundtrack (1003800) at "G:\Steam\steamapps\common\Gang Beasts Soundtrack"
0,3 - Steam: Found game Kerbal Space Program (220200) at "G:\Steam\steamapps\common\Kerbal Space Program"
0,3 - Steam: Found game Wreckfest (228380) at "G:\Steam\steamapps\common\Bugbear Entertainment"
0,3 - Steam: Found game Steamworks Common Redistributables (228980) at "G:\Steam\steamapps\common\Steamworks Shared"
0,3 - Steam: Found game Space Engineers (244850) at "G:\Steam\steamapps\common\SpaceEngineers"
0,3 - Steam: Found game SteamVR (250820) at "G:\Steam\steamapps\common\SteamVR"
0,3 - Steam: Found game Cities: Skylines (255710) at "G:\Steam\steamapps\common\Cities_Skylines"
0,3 - Steam: Found game Easy eSports (282660) at "G:\Steam\steamapps\common\EasyAntiCheat"
0,3 - Steam: Found game Gang Beasts (285900) at "G:\Steam\steamapps\common\Gang Beasts"
0,3 - Steam: Found game Automation - The Car Company Tycoon Game (293760) at "G:\Steam\steamapps\common\Automation"
0,3 - Steam: Found game DiRT Rally (310560) at "G:\Steam\steamapps\common\DiRT Rally"
0,3 - Steam: Found game Dishonored 2 (403640) at "G:\Steam\steamapps\common\Dishonored2"
0,3 - Steam: Found game 10 Second Ninja X (435790) at "G:\Steam\steamapps\common\10 Second Ninja X"
0,3 - Steam: Found game Crash Bandicoot™ N. Sane Trilogy (731490) at "G:\Steam\steamapps\common\Crash Bandicoot - N Sane Trilogy"
0,3 - Steam: Found game Accounting+ (927270) at "G:\Steam\steamapps\common\AccountingPlus"
0,3 - Steam: Found game Gang Beasts Soundtrack (1003800) at "g:/steam\steamapps\common\Gang Beasts Soundtrack"
0,3 - Steam: Found game Kerbal Space Program (220200) at "g:/steam\steamapps\common\Kerbal Space Program"
0,3 - Steam: Found game Wreckfest (228380) at "g:/steam\steamapps\common\Bugbear Entertainment"
0,3 - Steam: Found game Steamworks Common Redistributables (228980) at "g:/steam\steamapps\common\Steamworks Shared"
0,3 - Steam: Found game Space Engineers (244850) at "g:/steam\steamapps\common\SpaceEngineers"
0,3 - Steam: Found game SteamVR (250820) at "g:/steam\steamapps\common\SteamVR"
0,3 - Steam: Found game Cities: Skylines (255710) at "g:/steam\steamapps\common\Cities_Skylines"
0,3 - Steam: Found game Easy eSports (282660) at "g:/steam\steamapps\common\EasyAntiCheat"
0,3 - Steam: Found game Gang Beasts (285900) at "g:/steam\steamapps\common\Gang Beasts"
0,3 - Steam: Found game Automation - The Car Company Tycoon Game (293760) at "g:/steam\steamapps\common\Automation"
0,3 - Steam: Found game DiRT Rally (310560) at "g:/steam\steamapps\common\DiRT Rally"
0,3 - Steam: Found game Dishonored 2 (403640) at "g:/steam\steamapps\common\Dishonored2"
0,3 - Steam: Found game 10 Second Ninja X (435790) at "g:/steam\steamapps\common\10 Second Ninja X"
0,3 - Steam: Found game Crash Bandicoot™ N. Sane Trilogy (731490) at "g:/steam\steamapps\common\Crash Bandicoot - N Sane Trilogy"
0,3 - Steam: Found game Accounting+ (927270) at "g:/steam\steamapps\common\AccountingPlus"
0,3 - GOG: Found game Cyberpunk 2077 (1423049311) at "I:\GoG\Cyberpunk 2077"
0,3 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0,34 - EpicGamesStore: Found game PC Building Simulator at "H:\Epic\PCBuildingSimulator"
0,34 - EpicGamesStore: Found game Discord at "E:\Programme Windows\Programme\Discord"
0,34 - EpicGamesStore: Found game The Two Colonels at "F:\Epic Games\MetroExodus"
0,34 - EpicGamesStore: Found game Metro Exodus Enhanced Edition at "I:\Epic\MEEnhancedEdition"
0,34 - EpicGamesStore: Found game Metro Exodus at "F:\Epic Games\MetroExodus"
0,34 - EpicGamesStore: Found game Among Us at "H:\Epic\AmongUs"
0,34 - EpicGamesStore: Found game Sam's Story Enhanced Edition at "I:\Epic\MEEnhancedEdition"
0,34 - EpicGamesStore: Found game Oddworld: New 'n' Tasty at "F:\Epic Games\OddworldNewNTasty"
0,34 - EpicGamesStore: Found game Sam's Story at "F:\Epic Games\MetroExodus"
0,34 - EpicGamesStore: Found game The Two Colonels Enhanced Edition at "I:\Epic\MEEnhancedEdition"
0,34 - EpicGamesStore: Found game Absolute Drift at "F:\Epic Games\AbsoluteDrift"
0,34 - EpicGamesStore: Found game Red Dead Redemption 2 at "I:\Epic\RedDeadRedemption2"
0,35 - Origin: Found no Ids and Paths in the MFST files
0,49 - Wabbajack Version: 2.5.3.1
1 - Build server is down
1 - Build server is down
2,23 - Loading ModLists from GitHub
2,48 - Origin: Found game Battlefield 4 Pre-Order Edition - PCDD (WW) (OFB-EAST:109548960) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 Second Assault Expansion Pack - PDLC (Origin.com/3PDD) (OFB-EAST:109550761) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 China Rising Expansion Pack - PDLC -WW (Origin.com/3PDD) (OFB-EAST:109550763) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4: Dragon's Teeth Expansion Pack - PDLC - WW (Origin.com) (OFB-EAST:109550764) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 Naval Strike - PDLC - WW (Origin.com) (OFB-EAST:109550765) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4: Final Stand Expansion Pack - PDLC - WW (Origin.com) (OFB-EAST:109550823) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 China Rising Expansion Pack - PDLC -WW (Origin.com/3PDD) (Origin.OFR.50.0000366) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 Community Operations - DLC - WW (Origin.com) (Origin.OFR.50.0000909) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4 Night Operations - DLC - WW (origin.com) (Origin.OFR.50.0000910) at "F:\Origin Game\Battlefield 4"
2,48 - Origin: Found game Battlefield 4: Legacy Operations (XP7) - DLC - WW (Origin.com) (Origin.OFR.50.0000911) at "F:\Origin Game\Battlefield 4"
13,83 - Starting to install Elysium
13,83 - Cleaning VFS, this may take a bit of time
13,9 - Starting Installer Task
13,9 - Installation has Started
13,9 - Configuring Processor
13,9 - Install Folder: I:\SkyrimElysium
13,9 - Downloads Folder: E:\Wabbaajack Downloads
13,9 - Game Folder: I:\SteamLibrary\steamapps\common\Skyrim Special Edition
13,9 - Wabbajack Folder: E:\Skyrim Wabbaajack
13,91 - Drive watcher is starting. Will warn at 8GB and error at 4GB
13,91 - Starting Drive watcher on I:\ currently 456,4GB free out of 931,5GB
13,91 - Starting Drive watcher on E:\ currently 750,8GB free out of 1,8TB
13,91 - Validating Game ESMs
13,92 - Creating Output Folders
14,57 - Optimizing ModList
14,57 - Optimizing ModList directives
16,91 - Looking for files to delete
16,92 - Cleaning empty folders
17,61 - Looking for unmodified files
18,54 - Updating ModList
18,54 - Optimized 241594 directives to 241594 required
18,58 - Hashing Archives
18,58 - Looking for files to hash
18,79 - Found 1617 total files, 1542 matching filesize
19,07 - Downloading Missing Archives
19,07 - Missing 15 archives
19,07 - Getting Nexus API Key, if a browser appears, please accept
19,09 - Loading server whitelist
19,16 - Loaded permissions for 616 servers and 271 Google Drive files
19,17 - Downloading Data_Skyrim - Textures0.bsa
19,17 - Downloading Data_Skyrim.esm
19,17 - Downloading Data_Skyrim - Textures3.bsa
19,17 - Downloading Data_Skyrim - Sounds.bsa
19,2 - Downloading Data_Skyrim - Shaders.bsa
20,02 - Hashed download is incorrect
20,02 - Loading for alternative to yRcX3Ttf9YM=
20,07 - No alternative for yRcX3Ttf9YM= could be found
20,07 - Downloading Data_Skyrim - Patch.bsa
20,07 - (Retry 1 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 100ms
20,18 - (Retry 2 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 200ms
20,4 - (Retry 3 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 400ms
20,81 - (Retry 4 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 800ms
21,62 - (Retry 5 of 5), got exception (2) Das System kann die angegebene Datei nicht finden: [I:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\Skyrim - Patch.bsa], waiting 1600ms
22,28 - Hashed download is incorrect
22,31 - Loading for alternative to krNnq2qHmOo=
22,35 - No alternative for krNnq2qHmOo= could be found
22,35 - Downloading Data_Skyrim - Misc.bsa
23,23 - Loading for alternative to GG4pOfUmiRA=
23,27 - No alternative for GG4pOfUmiRA= could be found
23,27 - Downloading Data_Skyrim - Meshes1.bsa
25,28 - Hashed download is incorrect
25,28 - Loading for alternative to EwvbU7wcUUo=
25,32 - No alternative for EwvbU7wcUUo= could be found
25,32 - Downloading Data_Skyrim - Meshes0.bsa
37,6 - Hashed download is incorrect
37,6 - Loading for alternative to /Sglpr+ZffA=
37,64 - No alternative for /Sglpr+ZffA= could be found
37,64 - Downloading Data_Skyrim - Interface.bsa
40,91 - Hashed download is incorrect
40,91 - Loading for alternative to k5EWx/9Woqg=
40,95 - No alternative for k5EWx/9Woqg= could be found
40,95 - Downloading Data_Skyrim - Animations.bsa
42,72 - Hashed download is incorrect
42,72 - Loading for alternative to eN9rU4PSvEs=
42,77 - No alternative for eN9rU4PSvEs= could be found
42,77 - Downloading Data_Update.esm
43,35 - Hashed download is incorrect
43,35 - Loading for alternative to kX9UFltG4+s=
43,39 - No alternative for kX9UFltG4+s= could be found
43,39 - Downloading Data_HearthFires.esm
43,47 - Hashed download is incorrect
43,47 - Loading for alternative to /DLG/LjdGXI=
43,49 - No alternative for /DLG/LjdGXI= could be found
43,49 - Downloading Data_Dragonborn.esm
43,56 - Hashed download is incorrect
43,56 - Loading for alternative to GPdcQrqi2NI=
43,6 - No alternative for GPdcQrqi2NI= could be found
43,6 - Downloading Data_Dawnguard.esm
44,88 - Hashed download is incorrect
44,88 - Loading for alternative to CEgEhUUtOcU=
44,92 - No alternative for CEgEhUUtOcU= could be found
46,89 - Hashed download is incorrect
46,89 - Loading for alternative to eypuUwdQUb4=
46,93 - No alternative for eypuUwdQUb4= could be found
48,08 - Hashed download is incorrect
48,08 - Loading for alternative to rENi4TDkFjY=
48,13 - No alternative for rENi4TDkFjY= could be found
49,49 - Hashed download is incorrect
49,49 - Loading for alternative to 8LzXRU4x9Sw=
49,53 - No alternative for 8LzXRU4x9Sw= could be found
60,33 - Hashed download is incorrect
60,33 - Loading for alternative to XTaNNFIm3eM=
60,37 - No alternative for XTaNNFIm3eM= could be found
60,57 - Hashing Remaining Archives
60,57 - Looking for files to hash
61,72 - Found 1629 total files, 1540 matching filesize
61,94 - Unable to download Skyrim.ccc (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim.ccc)
61,94 - Unable to download SkyrimSE.exe (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrimse.exe)
61,94 - Unable to download Data_Dawnguard.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dawnguard.esm)
61,94 - Unable to download Data_Dragonborn.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\dragonborn.esm)
61,94 - Unable to download Data_HearthFires.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\hearthfires.esm)
61,94 - Unable to download Data_Update.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\update.esm)
61,94 - Unable to download Data_Skyrim - Animations.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - animations.bsa)
61,94 - Unable to download Data_Skyrim - Interface.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - interface.bsa)
61,94 - Unable to download Data_Skyrim - Meshes0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes0.bsa)
61,94 - Unable to download Data_Skyrim - Meshes1.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - meshes1.bsa)
61,94 - Unable to download Data_Skyrim - Misc.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - misc.bsa)
61,94 - Unable to download Data_Skyrim - Patch.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - patch.bsa)
61,94 - Unable to download Data_Skyrim - Shaders.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - shaders.bsa)
61,94 - Unable to download Data_Skyrim - Sounds.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - sounds.bsa)
61,94 - Unable to download Data_Skyrim.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim.esm)
61,94 - Unable to download Data_Skyrim - Textures3.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures3.bsa)
61,94 - Unable to download Data_Skyrim - Textures0.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|data\skyrim - textures0.bsa)
61,94 - Cannot continue, was unable to download one or more archives
65,14 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383

**Comment by EDDIE2Fast** [comment]
Found the Problem. The Patcher helps me: https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files
