### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by LofoWalker** [TitansBane/Elysium#251]
Hi dude ! First of all, thank you very much for the work you've done on that project it's amazing.
I'm trying to install Elysium with Wabbajack but it failed. I've got that error : 

```
1644,31 - Found 1805 total files, 1552 matching filesize
1644,5 - Unable to download xLODGen.84.7z (MegaDownloader+State|https://mega.nz/file/dEwQnJRS#E-qpq29rVCBw3FxT3gTOjF_Z2zYkzR2CcWhQ5OAZcwg)
1644,5 - Unable to download Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar (HTTPDownloader+State|https://github.com/ShikyoKira/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar)
1644,5 - Cannot continue, was unable to download one or more archives
1644,5 - File hash check (-42) dcedb2b436e71b5b1e4bd3dc927cff2ad31baf1524c135dac3ca370a3ca0d3d8
1644,51 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 217
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
1644,78 - File hash check (-42) dcedb2b436e71b5b1e4bd3dc927cff2ad31baf1524c135dac3ca370a3ca0d3d8
```

Can you help me ? I think the 2 archives reference there are no longer available ...

**Comment by LofoWalker** [comment]
Well ! I search and manualy download the files (Discord server is very usefull). I'm not block anymore ! Keep the issue open to help you fix that. Have a nice day

**Comment by mustafaulukaya** [comment]
Hi, can you drop the link for these archives? I faced the same error. When I find them, all I need is to copy these files into my Elysium/downloads folder, isn't it?

**Comment by Spacehonky** [comment]
Dropping here because these 2 files helped me as well. All I had to do was download them and manually place the NOT-EXTRACTED files into the Elysium download folder. Wabbajack then continued unimpeded.

**Comment by LofoWalker** [comment]
Oh yeah sorry guys it was stupid to not drop the links ...
