### ISSUE TITLE
Elysium not instaled Skyrim_Default.ini

### ISSUE THREAD

**Issue by avmer1980** [TitansBane/Elysium#268]
steam version SE, not UE
game languege russian
imstaled c:\game
game version 1.5.97.0.08
im use pather https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files

91,68 - Found 1579 total files, 1551 matching filesize
101,12 - Downloading Missing Archives
101,12 - Missing 1 archives
101,12 - Getting Nexus API Key, if a browser appears, please accept
101,12 - Loading server whitelist
101,21 - Loaded permissions for 642 servers and 284 Google Drive files
101,21 - File hash check (-42) da09f1f552112b4fba07efd582fbf5879f519ed97852a2e63c5a2e1a7f5817c4
101,22 - Downloading Skyrim_Default.ini
101,23 - Hashed download is incorrect
101,24 - Loading for alternative to JbYP1w8FSfY=
101,43 - No alternative for JbYP1w8FSfY= could be found
101,46 - Hashing Remaining Archives
101,46 - Looking for files to hash
101,57 - Found 1579 total files, 1551 matching filesize
101,72 - Unable to download Skyrim_Default.ini (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.5.97.0|skyrim_default.ini)
101,72 - Cannot continue, was unable to download one or more archives
101,72 - File hash check (-42) da09f1f552112b4fba07efd582fbf5879f519ed97852a2e63c5a2e1a7f5817c4
101,74 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
102,19 - File hash check (-42) da09f1f552112b4fba07efd582fbf5879f519ed97852a2e63c5a2e1a7f5817c4
[Wabbajack.current.log](https://github.com/TitansBane/Elysium/files/7891813/Wabbajack.current.log)

**Comment by avmer1980** [comment]
re dounload game whith english languege
elisium is working
bat i do not understand now? haw change for russian...

**Comment by avmer1980** [comment]
[Skyrim_Default.zip](https://github.com/TitansBane/Elysium/files/7892257/Skyrim_Default.zip)
if it need someone
whith this filw is working
