### ISSUE TITLE
Can't hash Skyrim_Particle_Patch_for_ENB-SSE.zip

### ISSUE THREAD

**Issue by Enforcer5981** [TitansBane/Elysium#72]
Hi, everything goes through except for this mod. 

`26.96 - Unable to download Skyrim_Particle_Patch_for_ENB-SSE.zip (GoogleDriveDownloader+State|12tL3_kpm_KXlQvQqEnK3zOAl-sm_H3Fw)
26.96 - Cannot continue, was unable to download one or more archives
26.96 - File hash check (-42) ec030c11b37394e22a1b3735dda2950069240acea75377f6725e3db29d26e74b
26.96 - Vacuuming databases
27.16 - File hash check (-42) ec030c11b37394e22a1b3735dda2950069240acea75377f6725e3db29d26e74b
27.8 - Vacuuming completed
27.81 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 156
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 373
`

**Comment by Ragura** [comment]
Encountered the same problem. Is the file no longer available for download?

**Comment by TheoriesBanana** [comment]
Same problem here, won't go too in-depth since it won't add anything to the thread. Seems like the mod download broke

**Comment by Arcthandus** [comment]
I have the same issue and it might be caused by a small update in the particle patch file. The updated file in question is "fxcameraattachblowingfog.nif" located in meshes -> effects and it seems to be the only recently changed file (updated in 30.3.2021). I might be wrong of course.

**Comment by GimlisGHOST** [comment]
I am having this same issue. It might have to do with google drive cant scan the file for viruses because its too big. Hopefully, we can get a fix soon so that we can enjoy this great work.

**Comment by m4s2firestorm** [comment]
Same issue, Trying to play the mod pack for first time guess i gotta wait :P

**Comment by Ragura** [comment]
Xanza on the Wabbajack Discord has supplied a temporary solution. You can fix the failed download by placing this file in the downloads folder of your installation: https://cdn.discordapp.com/attachments/717201285496963094/826462836062289920/Skyrim_Particle_Patch_for_ENB-SSE.zip

Worked for me!

**Comment by m4s2firestorm** [comment]
Can confirm fix, also worth noting you may need to delete the old file. A few people had this issue.

**Comment by Enforcer5981** [comment]
> Xanza on the Wabbajack Discord has supplied a temporary solution. You can fix the failed download by placing this file in the downloads folder of your installation: https://cdn.discordapp.com/attachments/717201285496963094/826462836062289920/Skyrim_Particle_Patch_for_ENB-SSE.zip
> 
> Worked for me!

Confirming this worked for me as well! Will leave this issue open unless asked to close or until Wabbajack can run the full install by itself again. Thank you.

**Comment by TitansBane** [comment]
Fixed for the next update.
